services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    environment:
      DB_URL: jdbc:postgresql://db:5432/appdb
      DB_USER: app
      DB_PASSWORD: app
    depends_on:
      - db
    ports:
      - "8081:8081"

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - "8082:80"

volumes:
  db-data:
